### PR TITLE
Fix protest list bug

### LINKED ISSUE #42: If you use device location and then change the address manually, the protest list doesn't change
See video in link.

https://www.screencast.com/t/tYbWLwX1VKWX

### PR DESCRIPTION
**Pull request by daganomri**
fixes #42, #55

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -22,7 +22,6 @@ const initialState = {
   mapPosition: [],
   mapPositionHistory: [],
   isModalOpen: true,
-  loading: true,
```
Comment (guytepper) [inline src/App.js:27]: Can you explain the reason for this?

**Review by guytepper — CHANGES_REQUESTED** [review]
Thanks! :)
Can you explain what was the issue and how you resolved it?

Also, check line 145 (and `ProtestList` too) - `loading` is being passed as a prop.

**Comment by daganomri** [comment]
I guess I missed some of the loadings 😅
Basically the loading state made it so protests are only fetched on initial load. After adding the change address button that was no longer necessary.

I can edit this tonight, or maybe you'll prefer just finishing it yourself and merging?

**Comment by daganomri** [comment]
On second thought, the solution could just be dispatching loading: true when changing address. The modal is already in the dispatch context so this should be easy.

**Comment by daganomri** [comment]
I edited from my phone, should work but I didn't test it.

File: src/App.js (hunk 1 above)
Comment (daganomri) [reply src/App.js:27]: Leaving a comment to resolve this as I explained it further in the pr

File: src/App.js [hunk 2]
```diff
@@ -108,7 +105,7 @@ function App() {
       }
       fetchProtests();
     }
-  }, [state.userCoordinates, state.mapPosition]);
+  }, [state.userCoordinates, state.mapPosition, state.mapPositionHistory, state.markers, state.loading]);
```
Comment (guytepper) [inline src/App.js]: Why do we need `state.mapPositionHistory, state.markers, state.loading` here? Is the effect depends on them?

Comment (daganomri) [reply src/App.js]: I think this comment is on not up-to-date code. I only put userCoordinates, mapPosition and markers (which I guess could be removed, I'll check it soon)

Comment (daganomri) [reply src/App.js]: I removed it from the up-to-date code

**Comment by guytepper** [comment]
I'm really sorry for the delay. Great work 🙂

**Comment by guytepper** [comment]
+HUGE performance boost. Here's a medal for you 🏅
