### PR TITLE
Fix: Protest List buttons - layout issue

### LINKED ISSUE #33: Protest List buttons - layout issue
Before protests show up & in case no protests are found, the sidebar looks like this:

Screen Shot 2020-10-05 at 15 29 30

The button should be at the top in all scenerios, like this:

Screen Shot 2020-10-05 at 15 33 40

### PR DESCRIPTION
**Pull request by daganomri**
I created a new ProtestListHead component for the semantic name, and for future styling options.

fixes #33

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -289,4 +291,8 @@ const ProtestListWrapper = styled.div`
   }
 `;
 
+const ProtestListHead = styled.div`
+  margin-bottom: 0.5rem;
```
Comment (guytepper) [inline src/App.js:295]: Better to use 8px - https://stackoverflow.com/a/11803273/3232187
(also in order to be consistent with the project)
